### ISSUE TITLE
☂️Umbrella: TypeScript migration

### ISSUE THREAD

**Issue by thymikee** [react-native-community/cli#683]
## Describe the Feature

Some time ago we started migrating CLI to TS package by package. The infrastructure is already set up, so we can work with TS and Flow files without issues.

Currently all packages except for `packages/cli` are converted. We need your help in converting the rest of the codebase 💪.

## Work plan

If you'd like to help with migrating any of the packages mentioned below, please leave a comment and we'll assign it to you.

### Commands

Commands live in separate directories. It makes sense to tackle them one by one.

- [x] commands/bundle (@Quadriphobs1)
- [x] commands/config (@netochaves)
- [x] commands/doctor (@thib92)
- [x] commands/info (@FLGMwt)
- [x] commands/init (@gvarandas)
- [x] commands/install (@DanielUche)
- [x] commands/link (@anikethsaha)
- [x] commands/server (@Esemesek)
- [x] commands/upgrade (@thymikee)
- [x] commands/index.js (@thymikee)

### Tools

Tools are helpers we use throughout  the `cli` package. They have corresponding test files, which can be found in `commands/tools/__tests__` directory. Those should also be converted.

- [x] commands/tools/assertRequiredOptions.js (@konojunya)
- [x] commands/tools/assign.js (@radko93)
- [x] commands/tools/brewInstall.js (@thymikee)
- [x] commands/tools/config/ (@ptrocki)
- [x] commands/tools/copyAndReplace.js (@luizcieslak)
- [x] commands/tools/copyFiles.js (@sasurau4)
- [x] commands/tools/findSymlinkedModules.js (@pveyes)
- [x] commands/tools/generator/ (@KangYoosam)
- [x] commands/tools/gracefulifyFs.js (@assuncaocharles)
- [x] commands/tools/install.js (@thymikee)
- [x] commands/tools/installPods.js (@thymikee)
- [x] commands/tools/isValidPackageName.js (@radko93)
- [x] commands/tools/loadMetroConfig.js (@radko93)
- [x] commands/tools/loader.js (@thymikee)
- [x] commands/tools/merge.js (@Naturalclar)
- [x] commands/tools/packageManager.js (@moriyuu)
- [x] commands/tools/releaseChecker/ (@FLGMwt)
- [x] commands/tools/replacePathSepForRegex.js (@FLGMwt)
- [x] commands/tools/walk.js (@FLGMwt)
- [x] commands/tools/yarn.js (@FLGMwt)

### Root index files in `src/`

Let's tackle this once we have all commands converted.

- [x] cliEntry.js, index.js, bin.js (@Esemesek)

**Comment by FLGMwt** [comment]
👋 Hey stranger ; D

I'm happy to give it a shot. I'd like to try to start with something small like `commands/info`. Could use some guidance about what to do about `ConfigT` from `types` which seems to be the only imported flow type.

**Comment by thymikee** [comment]
Hey! You can find shared types like `Config`, `Command` etc in `@react-native-community/cli-types` package.

**Comment by netochaves** [comment]
I would like to work in `config` if that's ok.

**Comment by thib92** [comment]
Would love to take the ˋdoctor` command!

**Comment by thymikee** [comment]
@netochaves @thib92 go for it!

**Comment by FLGMwt** [comment]
I was pulling the thread on tools/releaseChecker so I can pull that and replacePathSepForRegex + walk + yarn in too.

**Comment by gvarandas** [comment]
I can tackle the `commands/init` 🤖

**Comment by DanielUche** [comment]
I will like to tackle command/install

**Comment by Naturalclar** [comment]
I'd like to help with `commands/tools/merge.js`

**Comment by sasurau4** [comment]
I'd like to help with `commands/tools/copyFiles.js` 👍

**Comment by anikethsaha** [comment]
I can help with **`link`** command

**Comment by luizcieslak** [comment]
I'd like to work with `commands/tools/copyAndReplace.js`!

**Comment by pveyes** [comment]
I'd like to help with `command/tools/findSymlinkedModules.js` 👋

**Comment by konojunya** [comment]
I'd like to help with `commands/tools/assertRequiredOptions.js`💪

**Comment by moriyuu** [comment]
I'd like to help with `commands/tools/packageManager.js` !

**Comment by radko93** [comment]
I can do `loadMetroConfig.js`, `isValidPackageName.js` and `assign.js`

**Comment by thymikee** [comment]
There's only 5 files/directories left unassigned. You are amazing! 💕

**Comment by KangYoosam** [comment]
I'd like to help with `commands/tools/generator/` 😁

**Comment by assuncaocharles** [comment]
Hey, I do like to start helping with
```commands/tools/gracefulifyFs.js``` and then take something bigger. :D

Btw, it seems ```commands/tools/install.js``` is done

**Comment by Quadriphobs1** [comment]
I'd like to help with `commands/bundle` 😄

**Comment by ptrocki** [comment]
I would like to help with `commands/tools/config/`

**Comment by Noeza** [comment]
I would like to help if there are any files left, not yet taken

**Comment by thymikee** [comment]
@Noeza you could take a look at __e2e__ directory and convert tests. We would also use some help with reviewing PRs :)

**Comment by nitaking** [comment]
I want to raise my hand for the next help!

**Comment by Sly777** [comment]
I can also help with code review or for converting tests.

**Comment by nickytonline** [comment]
Anything else to grab? I [helped migrate the Refined GitHub extension](https://github.com/sindresorhus/refined-github/commits?author=nickytonline) to TS. Happy to work on any part of this.

**Comment by thymikee** [comment]
Looks like we're out of work that's not assigned to anybody. But maybe we missed something, so feel free to identify that. If not, code review is always welcome. Or PRs improving type coverage!

**Comment by ptrocki** [comment]
@nitaking @Sly777 @nickytonline 
I am struggling with this PR https://github.com/react-native-community/cli/pull/710 . Can you help me with this ?

**Comment by nickytonline** [comment]
I'll take a peek tonight @ptrocki.

**Comment by grabbou** [comment]
We have just replaced the remaining files as a part of #783.
